<div class="d4p-group d4p-group-changelog">
    <h3><?php _e("Version", "gd-rating-system"); ?> 1</h3>
    <div class="d4p-group-inner">
        <h4>Version: 1.3 - Pallas / august 24 2016</h4>
        <ul>
            <li><strong>new</strong> addon: Feeds - for RSS, AMP, FIP, ANF integration support</li>
            <li><strong>new</strong> font icons: support for adding custom icon fonts</li>
            <li><strong>new</strong> font icons: 10 more icons in default icons font</li>
            <li><strong>new</strong> rewriten handling for the font icons</li>
            <li><strong>new</strong> allow or prevent authors to vote for own rating items</li>
            <li><strong>new</strong> improved sanitation of plugins settings on save</li>
            <li><strong>new</strong> transfer data from KK Star Ratings plugin</li>
            <li><strong>new</strong> actions run when voting items data is saved to the database</li>
            <li><strong>new</strong> filter to modify votes meta data added to the database</li>
            <li><strong>new</strong> ratings and votes grids allow for adding of new columns</li>
            <li><strong>new</strong> support for IP detection when behind CloudFlare</li>
            <li><strong>edit</strong> improved sanitation of plugins settings on save</li>
            <li><strong>edit</strong> improved buttons on all dialogs on the admin side</li>
            <li><strong>edit</strong> many improvements in handling shortcodes and widgets</li>
            <li><strong>edit</strong> ratings grid proper use of the rating item objects</li>
            <li><strong>edit</strong> many small improvements to the JavaScript code</li>
            <li><strong>edit</strong> d4pLib 1.7.8</li>
            <li><strong>fix</strong> few small issues when the user agent is not set</li>
            <li><strong>fix</strong> saving option to disbale custom settings rule not working</li>
            <li><strong>fix</strong> few minor styling issues related to rating lists</li>
            <li><strong>fix</strong> warnings generated by the missing style type and/or name</li>
            <li><strong>fix</strong> logs display warnings with post types are missing</li>
            <li><strong>fix</strong> small issue with type option in the shortcodes processing</li>
            <li><strong>fix</strong> duplicated classes added for star rating font icons styles</li>
            <li><strong>fix</strong> minor problems in applying default styles for widgets</li>
            <li><strong>fix</strong> few minor problems with the main JavaScript file</li>
            <li><strong>fix</strong> warnings related to query object SQL query in some cases</li>
            <li><strong>fix</strong> wrong attribute name for item ID for some shortcodes</li>
        </ul>

        <h4>Version: 1.2 - Helios / may 10 2016</h4>
        <ul>
            <li><strong>new</strong> posts addon: sort posts by rating</li>
            <li><strong>new</strong> posts addon: additional control filters</li>
            <li><strong>new</strong> comments addon: sort posts by rating</li>
            <li><strong>new</strong> comments addon: additional control filters</li>
            <li><strong>new</strong> query engine: posts filter by author, meta and terms</li>
            <li><strong>new</strong> query engine: comments filter by author and meta</li>
            <li><strong>new</strong> query engine: terms filter by meta</li>
            <li><strong>new</strong> query engine: users filter meta</li>
            <li><strong>new</strong> debug information added for shortcodes and widgets</li>
            <li><strong>new</strong> separate security and debug settings panels</li>
            <li><strong>new</strong> settings panel now uses dividers for settings groups</li>
            <li><strong>edit</strong> posts addon: do not embed if inside the rss feed</li>
            <li><strong>edit</strong> new settings and updates for rendering of rating blocks</li>
            <li><strong>edit</strong> protect expanded rendering functions</li>
            <li><strong>edit</strong> extra information for transfer data panels</li>
            <li><strong>edit</strong> check if method is active for transfer data panels</li>
            <li><strong>edit</strong> minor updates to some of the templates</li>
            <li><strong>edit</strong> some minor improvements on the admin side interface</li>
            <li><strong>edit</strong> d4pLib 1.6.9</li>
            <li><strong>fix</strong> minor issue with the GD Star Rating transfer process</li>
            <li><strong>fix</strong> comments addon: rating display when no comment is detected</li>
            <li><strong>fix</strong> posts addon: rating display when no comment is detected</li>
            <li><strong>fix</strong> small issue with the d4pLib shortcodes class</li>
        </ul>
        <h4>Version: 1.1.1 / january 23 2016</h4>
        <ul>
            <li><strong>new</strong> front page knowledge base and support links</li>
            <li><strong>edit</strong> check for rating method validity before render</li>
            <li><strong>edit</strong> few minor updates to the default styling</li>
            <li><strong>fix</strong> templates in theme subfolder 'gdrts' not loaded</li>
        </ul>
        <h4>Version: 1.1 / january 18 2016</h4>
        <ul>
            <li><strong>new</strong> stars rating: set custom colors for font icons based stars</li>
            <li><strong>new</strong> daily maintenance background job</li>
            <li><strong>new</strong> background job: calculate rating type based statistics</li>
            <li><strong>new</strong> background job: recalculate ratings on stars number change</li>
            <li><strong>edit</strong> rating query object allows filtering of query elements</li>
            <li><strong>edit</strong> main posts metabox improves default filters and actions</li>
            <li><strong>edit</strong> font icons: includes spinner icon and some extra classes</li>
            <li><strong>edit</strong> font icons: font files included with plugin version parameter</li>
            <li><strong>edit</strong> posts integration addon shows help for the addon</li>
            <li><strong>edit</strong> posts integration addon hides bbPress post types</li>
            <li><strong>edit</strong> d4pLib 1.5.8</li>
            <li><strong>fix</strong> comment rating type missing title when display in lists</li>
            <li><strong>fix</strong> using FontAwesome spinner icon for loading message</li>
            <li><strong>fix</strong> method and addon issues with missing custom rule values</li>
            <li><strong>fix</strong> several smaller issues with the admin interface</li>
            <li><strong>fix</strong> problems with rating lists ordering by votes</li>
        </ul>
        <h4>Version: 1.0.3 / january 4 2016</h4>
        <ul>
            <li><strong>edit</strong> some addons function moved into plugin core</li>
            <li><strong>edit</strong> improvements to some rendering functions</li>
            <li><strong>edit</strong> switched to new admin object base class from D4PLib</li>
            <li><strong>edit</strong> d4pLib 1.5.6</li>
            <li><strong>fix</strong> extensions panel allows for all methods to be disabled</li>
            <li><strong>fix</strong> rich snippet addon: broken if selected method is disabled</li>
            <li><strong>fix</strong> rating method dropdown lists show disabled methods</li>
        </ul>
        <h4>Version: 1.0.2.1 / december 29 2015</h4>
        <ul>
            <li><strong>fix</strong> abstract method class inheritance problem</li>
        </ul>
        <h4>Version: 1.0.2 / december 28 2015</h4>
        <ul>
            <li><strong>edit</strong> improvements to loading of the templates list</li>
            <li><strong>edit</strong> d4pLib 1.5.5</li>
            <li><strong>fix</strong> deleting custom rules not working</li>
            <li><strong>fix</strong> showing disabled methods and addons on rules panel</li>
            <li><strong>fix</strong> loading conflict with GD bbPress Toolbox Pro</li>
            <li><strong>fix</strong> minor metabox initialization issue</li>
        </ul>
        <h4>Version: 1.0.1 / december 27 2015</h4>
        <ul>
            <li><strong>new</strong> metabox for posts to override embed settings</li>
            <li><strong>edit</strong> plugin initialization priority changed</li>
        </ul>
        <h4>Version: 1.0 / december 23 2015</h4>
        <ul>
            <li><strong>new</strong> first official version</li>
        </ul>
    </div>
</div>
